<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Swasta</name>
   <tag></tag>
   <elementGuidId>776497f4-710b-4f35-9f0b-e9311b111069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portfolio-dropdown-jenis-sistem']/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0e2c14c-fb24-4a3f-9973-5e77f63eb034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://javan.co.id/portfolio?client_type_id=3</value>
      <webElementGuid>0134a2b6-c09b-4555-b966-0505c98c3bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block hover:bg-primary hover:text-white pl-4 py-1.5</value>
      <webElementGuid>01d01645-a101-4cfc-a45f-fc8ffde21448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>b5c97087-8adc-4610-b8fe-f3b2d3453740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Swasta</value>
      <webElementGuid>e96f4f53-c830-4010-b8c0-e9a0b84a3941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portfolio-dropdown-jenis-sistem&quot;)/div[@class=&quot;font-nunito font-semibold text-base text-black-50%&quot;]/a[@class=&quot;block hover:bg-primary hover:text-white pl-4 py-1.5&quot;]</value>
      <webElementGuid>8d01bee6-d75d-4800-a645-0eeb59457831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portfolio-dropdown-jenis-sistem']/div/a[3]</value>
      <webElementGuid>bea79fb6-be8a-40c7-9d63-8cca2be74c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Swasta')]</value>
      <webElementGuid>6ce3020d-1fb7-43f0-be38-b4c32af5c39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K/L (Kementerian/Lembaga) Daerah'])[1]/following::a[1]</value>
      <webElementGuid>9c3464c4-1ac5-4a0e-8cef-f7b270e9cb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K/L (Kementerian/Lembaga) Pusat'])[1]/following::a[2]</value>
      <webElementGuid>3121cd80-4a4e-4ea3-9104-37fe9d110cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perguruan Tinggi Negeri'])[1]/preceding::a[1]</value>
      <webElementGuid>fc3b570c-8b93-4a89-b7e9-c250f8e51bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perbankan'])[1]/preceding::a[2]</value>
      <webElementGuid>ae48738d-c30f-4fdf-8812-a8b33e1e93e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Swasta']/parent::*</value>
      <webElementGuid>d5fc3ee5-01f3-4598-abf4-be21f0c49947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://javan.co.id/portfolio?client_type_id=3')]</value>
      <webElementGuid>3a715690-796f-45e9-bf74-2123070749fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a[3]</value>
      <webElementGuid>4d0fc16e-5ea4-4ea4-8613-d91ec0576395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://javan.co.id/portfolio?client_type_id=3' and (text() = 'Swasta' or . = 'Swasta')]</value>
      <webElementGuid>866e731d-9198-456a-addd-35ffeb6d88a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
